### ISSUE TITLE
Support QCA9377

### ISSUE THREAD

**Issue by oybekrustamov** [ipang-dwi/atheros#2]
Hi dear friend(friends). Can you also write for the QCA9377 card? Many would be grateful for your work. The sources are in my repositories, thank you!
[Link pero qca9377 source](https://github.com/oybekrustamov/qca9377_fully_source)

**Comment by ipang-dwi** [comment]
> Hi dear friend(friends). Can you also write for the QCA9377 card? Many would be grateful for your work. The sources are in my repositories, thank you!
> [Link pero qca9377 source](https://github.com/oybekrustamov/qca9377_fully_source)

sorry to inform you that there is  no kext available till now for your wifi card QCA9377, you can use the option to replace your wifi card with another compatible and working well wifi card. need a long process to develop kext for each hardware in osx, and apple didn't give us open source library for it. :)

**Comment by oybekrustamov** [comment]
> sorry to inform you that there is no kext available till now for your wifi card QCA9377, you can use the option to replace your wifi card with another compatible and working well wifi card. need a long process to develop kext for each hardware in osx, and apple didn't give us open source library for it. :)

Hi. Thank you for answering. I think that this will help you, although you will not be able to write under my card, but it can be useful for other purposes. And we will keep THE qca9377 card up to date for the time being)
[LINK developer.apple.com](https://developer.apple.com/library/archive/documentation/Darwin/Conceptual/NKEConceptual/intro/intro.html)

**Comment by ipang-dwi** [comment]
> > sorry to inform you that there is no kext available till now for your wifi card QCA9377, you can use the option to replace your wifi card with another compatible and working well wifi card. need a long process to develop kext for each hardware in osx, and apple didn't give us open source library for it. :)
> 
> Hi. Thank you for answering. I think that this will help you, although you will not be able to write under my card, but it can be useful for other purposes. And we will keep THE qca9377 card up to date for the time being)
> [LINK developer.apple.com](https://developer.apple.com/library/archive/documentation/Darwin/Conceptual/NKEConceptual/intro/intro.html)

Ok, let's me give little explain to you. 
1. Your reference given above is out of date, you can read it by it's footnote, it has been wrote on 2012 and never got update after that. So, what you wanna to "qca9377 card up to date for the time being". Up to date is a condition, if the hardware become get update periodically from apple developer or community over the world. And what you can see, although apple, didn't release update for it. I am sorry but the status for this card is eol - end of life.
2. Your reference can't help me, beside is too old reference and never got update again from apple developer. Sorry, but I am basically a web developer, not a mechanical engineer, so I can't do that. What I can do in thi repo is just a custom from working kext from another osx version before. I just use my little knowledge, to customize it, because I have some of them too.
3. I don't have qca9377 card, I am never see people around me having it too. So, how I can try your reference.
=====
So, as I can suggest before, just try another working wifi card, and I am never to add another not working wifi card to my repo. But thanks to message me about it.

**Comment by oybekrustamov** [comment]
OK, I understand, thank you.

**Comment by ipang-dwi** [comment]
> OK, I understand, thank you.
yap, I will close this issue..
