### ISSUE TITLE
Slow Speeds on Wifi Atheros 9485

### ISSUE THREAD

**Issue by ashishpatel1992** [ipang-dwi/atheros#3]
I have Atheros 9485, originally Dells DW1703
At `System Information > Network > Wi-Fi`, it shows max Transmit rate as 11Mbps, Tried connecting to different routers and also through mobile hotspot the Transmit Rate is 11 Mbps as advertised in the settings page.

Although when I tested my internet speed from MAC its around 1.45-2.8Mbps, while my internet connection is of 50Mbps and I easily get around 45-50 Mbps on Windows Machine.

I am on macOS Catalina 10.15.6 and using Release `https://github.com/ipang-dwi/atheros/releases/download/1.0/IO80211Family.kext.zip`

I am using open core and my config.plist is attached.[https://pastebin.com/3dj2R8h8](url)

**Comment by ipang-dwi** [comment]
Sorry to inform you that I didn't test it using opencore yet.. So, I can't give solution for your problem..

**Comment by ashishpatel1992** [comment]
I think it doesn't make any difference if you use OpenCore or Clover as per my experience. All that matters is the configuration of the system.

**Comment by ipang-dwi** [comment]
Bro, that's LOL.. Yes, you say, "I think it doesn't make any difference if you use OpenCore or Clover as per my experience. All that matters is the configuration of the system.".. If you mean it is the setting of your opencore, so how I can give you the solution about it, as I say I am never use opencore, so you must try to solve your problem by yourself.. May you try the latest release from this repo, none like your first post use.. Check this out https://github.com/ipang-dwi/atheros/releases/download/v2/ar9485_v2.072020.7z On that second release, some of my friends just test it on their Asus and Dell laptop, and yes it works flawlessly.. Umm, one more, AR9485 is use core kext library from old osx version, if I don't forget to remember, el capitan or sierra, and after that there is no official or community developer update from where ever.. Sometimes it tweaks personally just for one specific laptop, like me, because I didn't have another laptop that supported osx well, so I didn't grant that all users that use my kext will get same output.. As we know, osx need specific setup for each specific hardware used.. I hope you can get luck with another kext.. Btw osx is not my daily os, as I use and tweak it just in spare time.. My daily os is linux..

**Comment by ashishpatel1992** [comment]
Hello,
Well I have tried the v2 release as well and there are no improvements in speed, instead, I guess it now shows real Transmit Rate as 5Mbps. I was looking for source code but couldn't find that in the above library. If you know the source code for IO80211Family.kext do share with me. I will see if I can tweak something to make it work!
